In [ ]:
#기초 문법

# 문자형
a = 1 # %d 정수
b = 3.3 # %f 실수(소수6자리), %0.2f 실수(소수2자리)
c = "python" # %s 문자열
d = "Programming" # %c 단일문자

#문자열 내장함수
str = "Python programming"
print(str.count('p')) #count() 특정 문자 개수 세기
print("/".join(str)) # join() 문자열 삽입
print(str.find('m')) # find() 찾는 문자열이 처음 나온 위치 반환
print(str.upper()) # upper() 대문자로 변환
print(str.lower()) # lower() 소문자로 변환
print(str.replace("Python", "Java")) # replace(원본, 바꿀것) 특정 값 변환
print(str.split()) # split() 공백 기준(입력값)으로 분리

#연산자
a, b = 10, 5
print(a//b) # // - 몫
print(a%b) # % - 나머지
print(a**b) # ** - 거듭제곱
print(a != b) # != - 같지 않다


1
P/y/t/h/o/n/ /p/r/o/g/r/a/m/m/i/n/g
13
PYTHON PROGRAMMING
python programming
Java programming
['Python', 'programming']
2
0
100000
True


In [ ]:
# 가장 큰 수 찾기
a = int(input("첫번째 수를 입력하세요.")) # input하면 string으로 나와서 int함수로 감싸줘야함
b = int(input("두번째 수를 입력하세요."))
c = int(input("세번째 수를 입력하세요."))

if (a>=b):
  big = a
else:
  big = b

if (c>=big):
  print("가장 큰 수는 {0}입니다.".format(c)) # print("가장 큰 수는 %d입니다." %c)

else:
  print("가장 큰 수는 {0}입니다.".format(big))

KeyboardInterrupt: ignored

In [ ]:
# 반복문
for i in range(5):
  print("Python programming")

sum = 0
for i in range(1,6): #1~5
  sum += i
  print("i의 값 : %d, 합계 : %d" %(i,sum))

for i in range(1,10,2):
  print(i, end = ' ')

print() # 줄바꿈

for x in "python": # 문자열 출력
  print(x)

for i in range(1,5):
  for j in range(1,5):
    print(i * j, end = ' ')
  print() # i 가 바뀌는 시점에 줄바꿈

###################################

i = 1
while i <= 5:
  print("python programming")
  i += 1

i = 0
s = "python programming"
while i <= (len(s) - 1): #len() 길이 추출
  print(s[i], end = ' ')
  i += 1

print()
i = 0
while i <= 100:
  print(i, end = ' ')
  i += 1
  if i == 10:
    break


Python programming
Python programming
Python programming
Python programming
Python programming
i의 값 : 1, 합계 : 1
i의 값 : 2, 합계 : 3
i의 값 : 3, 합계 : 6
i의 값 : 4, 합계 : 10
i의 값 : 5, 합계 : 15
1 3 5 7 9 
p
y
t
h
o
n
1 2 3 4 
2 4 6 8 
3 6 9 12 
4 8 12 16 
python programming
python programming
python programming
python programming
python programming
p y t h o n   p r o g r a m m i n g 
0 1 2 3 4 5 6 7 8 9 

In [ ]:
# 리스트
a = []
a = [1,2,3,4,5]
print(a)
print(a[0], a[-1], a[0] + a[2])
print(a*3) # 리스트 * n = n번만큼 리스트 반복

a.append('a') # append - 맨 끝에 원소 추가
a.insert(1,'b') # insert(인덱스, 원소) - 특정 인덱스에 원소값 추가
print(a)
del a[1]
print(a) # del a[] - 해당 인덱스 원소 삭제


a = ['a','b','c','d','e']

a.reverse() # 역순으로 만들기
print(a)

print(a.index('b')) # 원하는 원소 인덱스 추출

a.sort() # 정방향으로 순서
print(a)

print(a.index('b'))

print(a.count('a')) # 원소 갯수 세기
a.remove('a') # 지정 원소 제거
print(a)


a = ['a','b','c']
for x in a:
  print(x, end = ' ')

print()
i = 0
while i < len(a):
  print(a[i], end = ' ')
  i += 1

print()
# 2차원 리스트 - 인덱스 2개 설정 가능
score = [[70,75], [80,90], [100,90], [95,85], [82,92]]
print(score[0][0])
print(score[0][1])
print(score[2][0])

[1, 2, 3, 4, 5]
1 5 4
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 'b', 2, 3, 4, 5, 'a']
[1, 2, 3, 4, 5, 'a']
['e', 'd', 'c', 'b', 'a']
3
['a', 'b', 'c', 'd', 'e']
1
1
['b', 'c', 'd', 'e']
a b c 
a b c 
70
75
100


In [ ]:
# 튜플 - 리스트와 유사하지만 값 변경 불가능
t = ('a','b','c','d','e')
print(t[0])
print(t[2:])
print(t * 2) #2번 반복
print(len(t))

# 딕셔너리 - 키(key):값(value)
dic1 = {1:'a', 2:'b', 3:'c'}
dic2 = {'name':'python', 'age':30,'job':'programming'}
print(dic1[1]) # 키 값에 해당하는 값 출력
print(dic2['age'])

dic1[5] = 'e' # 키 값에 해당하는 값 추가
print(dic1)
dic2['contact'] = 'python.org'
print(dic2)

print(dic1.keys()) # keys, values, items
print(dic1.values())
print(dic1.items())

if 'age' in dic2:
  print(dic2.get('age')) # get('키') -> 값 출력


a
('c', 'd', 'e')
('a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e')
5
a
30
{1: 'a', 2: 'b', 3: 'c', 5: 'e'}
{'name': 'python', 'age': 30, 'job': 'programming', 'contact': 'python.org'}
dict_keys([1, 2, 3, 5])
dict_values(['a', 'b', 'c', 'e'])
dict_items([(1, 'a'), (2, 'b'), (3, 'c'), (5, 'e')])
30


In [ ]:
id_pass = {'cuk':'12ab','python':'11aa','bigdata':'cc21'}
id = input("아이디를 입력하세요.")
password = input("비밀번호를 입력하세요.")

if id in id_pass:
  if password == id_pass.get(id):
    print("아이디와 비밀번호가 맞습니다.")
  else:
    print("비밀번호가 틀립니다.")
else:
  print("아이디가 존재하지 않습니다.")

KeyboardInterrupt: ignored

In [ ]:
# 함수, 라이브러리(모듈, 패키지)
def sum(x,y):
  return x + y

print(sum(3,5))

def f1(x):
  if x % 2 == 0 :
    return("짝수")
  else:
    return("홀수")

# x = int(input("홀짝판별기"))
# print("{0}은 {1} 입니다.".format(x, f1(x)))

def f2(x,y):
  return x*y

print(f2(2,4))

8
8


In [ ]:
# Numpy - 행렬이나 다차원 배열 분석, 배열 특화
import numpy as np

ar1 = np.array([1,2,3,4,5])
ar2 = np.array([[1,2,3],[4,5,6]]) # 2차원 배열
print(ar1)
print(ar2)

ar3 = np.random.randn(3) # 난수
ar4 = np.random.randn(2,3)
print(ar3)
print(ar4)

ar5 = np.zeros(5)
ar6 = np.zeros((2,3))
print(ar5)
print(ar6)

ar7 = np.arange(20,200,10) # arange(처음,마지막-간격,간격)
ar8 = ar7.reshape(3,6)
print(ar7)
print(ar8)

ar9 = np.arange(1,11)
print(ar9)
print(ar9+3,"\n",ar9*2,"\n") # 줄바꿈 "\n"

ar10 = np.array([[5,7,9],[-7,-6,19],[6,9,11]])
print(ar10)
print(ar10.sum())
print(ar10.mean())
print(ar10.max())
print(ar10.min())
print(ar10.max(axis=0)) # axis=0 - 배열의 각 열 원소 중 가장 큰 값
print(ar10.max(axis=1)) # axis=1 - 배열의 각 행 원소 중 가장 큰 값

print()
print(ar10 > 0)
sum_count = (ar10 > 0).sum()
print(sum_count)

ar11 = np.where(ar10 < 0, 0, ar10) # np.where(조건, 조건 만족 시 반환 값, 조건 만족 x 시 반환 값)
print(ar11)

print()
ar10.sort(0) # 열 단위 오름차순
print(ar10) # print() 안에 ar10.sort(0) 넣으면 None 출력
ar10.sort(1)
print(ar10) #행 단위 오름차순

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[ 1.78676271 -0.45001192  0.29683464]
[[-1.03166894 -0.28184062 -0.17269812]
 [-0.99800387 -1.12209862 -1.49380879]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]
[[ 20  30  40  50  60  70]
 [ 80  90 100 110 120 130]
 [140 150 160 170 180 190]]
[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10 11 12 13] 
 [ 2  4  6  8 10 12 14 16 18 20] 

[[ 5  7  9]
 [-7 -6 19]
 [ 6  9 11]]
53
5.888888888888889
19
-7
[ 6  9 19]
[ 9 19 11]

[[ True  True  True]
 [False False  True]
 [ True  True  True]]
7
[[ 5  7  9]
 [ 0  0 19]
 [ 6  9 11]]

[[-7 -6  9]
 [ 5  7 11]
 [ 6  9 19]]
[[-7 -6  9]
 [ 5  7 11]
 [ 6  9 19]]


In [ ]:
#판다스 - 데이터 분석, 테이블 형식(행,열)의 데이터 특화
import pandas as pd

sr1 = pd.Series([10,30,20,40,60], index = ['a','b','c','d','e']) # Series - series로 입력하니 오류출력
print(sr1)
print(sr1.values)
print(sr1.index)
print(sr1[2])

print(sr1[1]) # 아래와 같은 값
print(sr1['b'])

print(sr1[[1,2]]) #[[]] 해줘야 [1], [2] 출력
print(sr1[['a','b']])
print(sr1[:4]) # 0 ~ 3
print(sr1['a':'d']) # a~d 까지(슬라이싱x)

a    10
b    30
c    20
d    40
e    60
dtype: int64
[10 30 20 40 60]
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
20
30
30
b    30
c    20
dtype: int64
a    10
b    30
dtype: int64
a    10
b    30
c    20
d    40
dtype: int64
a    10
b    30
c    20
d    40
dtype: int64


In [ ]:
# Pandas 데이터프레임
df1 = pd.DataFrame([[10,20,30],[40,50,60]]) #소문자 dataframe 안댐
print(df1)
print()

dic1 = {'fruit' : ['사과', '배', '감','귤','바나나'],
        'price' : [100,200,150,50,200],
        'qty' : [10,25,30,25,15]}
df2 = pd.DataFrame(dic1, index = ['a','b','c','d','e'])
print(df2)
print()

df2.rename(columns = {'fruit':'과일','price':'가격','qty':'수량'}, inplace=True) # inplace=Treu 생략 시, 새로운 객체를 생성해서 변환
df2.rename(index = {'a':0,'b':1,'c':2,'d':3,'e':4}, inplace=True)
print(df2)

    0   1   2
0  10  20  30
1  40  50  60

  fruit  price  qty
a    사과    100   10
b     배    200   25
c     감    150   30
d     귤     50   25
e   바나나    200   15

    과일   가격  수량
0   사과  100  10
1    배  200  25
2    감  150  30
3    귤   50  25
4  바나나  200  15


In [23]:
# import pandas as pd
# from google.colab import drive
# drive.mount('/content/drive')

df1 = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/빅데이터분석기사예제/df_sample.csv')
print(df1.head(5)) #위에 5개만 보기
df1.shape #(행, 열) 수
#print(df1.info()) # string -python = object - pandas
df1.count() #열별 데이터 수
df1.describe(include='all') #기술통계 요약, top = 가장 많이 나타나는 데이터 -> freq = 그 빈도
df1['중간'].mean()
df1[['중간','기말']].mean()
df1['학번'].min()
df1.median() # 숫자형에만 적용
df1[['중간','기말']].std()
df1[['중간','기말']].var()

df1['퀴즈'].value_counts() # 값의 갯수
df1[['중간','기말']].corr() # 두 열 상관계수 출력
df1.corr() # 모든 열 상관계수

# df1.set_index('학번', inplace = True) #df1.reset_index(), inplace = True 입력 시, 변경사항이 반영됨
# print(df1.loc['S01','중간']) # .loc[인덱스명,열이름]에 해당하는 값 출력
# print(df1.loc['S05'])

print(df1.iloc[1,0], df1.iloc[1,1], df1.iloc[1,2]) # .iloc[인덱스번호, 열번호]
print(df1.iloc[4])

df1['중간']
df1[['중간','기말']]

df2 = df1.drop(0) # 인덱스 0행 삭제
df3 = df2.drop('퀴즈', axis=1) # '퀴즈' 열 삭제, 기본 설정은 행 삭제이므로 axis=1 추가 시 열 삭제

df1.set_index('학번', inplace = True)
df2 = df1.sort_index(ascending=False) # 인덱스 내림차순 정렬
df2 = df1.sort_values(by = '기말', ascending = True) # 열 기준(기말) 오름차순 정렬


df1["합계"] = df1["중간"] + df1["기말"]
x = ["1반","1반","1반","2반","2반","2반","3반","3반","3반","3반"]

df1["cls"] = x
# df1.insert(6,"cls",x,True)
# df1.assign(cls = x)
# df1.loc[:,'cls'] = x

import numpy as np
#Z스코어
mid_avg = np.mean(df1["중간"])
mid_std = np.std(df1["중간"])
df1["중간_Z점수"] = (df1["중간"] - mid_avg) / mid_std # Z스코어 열 생성

#정규화
fin_min = np.min(df1["기말"])
fin_max = np.max(df1["기말"])
df1["기말_정규화"] = (df1["기말"] - fin_min) / (fin_max - fin_min)

#그룹화
df1_cls_grp = df1.groupby(df1['cls'])
df1_cls_grp.mean() # 그룹별 평균
df1['중간'].groupby(df1['cls']).count() # '중간'열에서 'cls' 빈도 수
df1["퀴즈"].apply(np.sqrt) # 퀴즈 열에 함수(루트) 적용

#결측값
x = [14,15,13,14,None,None,19,11,12,18]
df1["토론"] = x
# df1.info()
# df1.isnull() # Null = True
# df1.notnull() # Null = False
df1_new = df1.dropna(axis=0) # 결측값 제거 - axis = 0 (행 전체), axis = 1 (열 전체)
df1_new = df1["토론"].dropna() # 열에서 결측값 제거

d_mean = df1["토론"].mean()
df1["토론"].fillna(d_mean, inplace = True) # 결측값 채우기

#이상치 판별 - (1사분위수 - 1.5*사분위범위)보다 작거나 (3사분위수 + 1.5*사분위범위) 보다 큰 수
df1_1QR = df1["기말"].quantile(0.25) # 1사분위수
df1_3QR = df1["기말"].quantile(0.75) # 3사분위수
df1_IQR = df1_3QR - df1_1QR # 사분위범위
# print(df1_IQR)


    학번  중간  기말  리포트  퀴즈
0  S01  90  95   20  20
1  S02  82  83   18  18
2  S03  80  78   18  18
3  S04  78  75   10  10
4  S05  93  91   12  12
S02 82 83
학번     S05
중간      93
기말      91
리포트     12
퀴즈      12
Name: 4, dtype: object
7.25


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  
